# Generated by Django 5.0.4 on 2024-04-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
